### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Krakean** [bbougot/libtorrent-net#2]
Hello!
First of all, wanted to say thanks to you for continue work on libtorrent-net. Have to write it here, because cannot see any other ways to contact with you.

And, a few questions:
1. Is it compatible with latest libtorrent RC_1_1 branch? Or only vanilla 1.1.3?
2. Do you have plans to keep updating it with newly libtorrent version?
3. Is this library contains any drawbacks to original libtorrent library? Is it full api, or there is something that has been not "binded" to .net?

Thanks for your attention

**Comment by bbougot** [comment]
Hi!
No problem, I am glad to enlighten you.

Before answering your questions, I have to tell you this fork is, at this time, exclusively developed by myself in the context of an other project I own (https://github.com/bbougot/Popcorn).

Hence, I am porting only a very small part of the libtorrent's API.

As regards your questions:

1. I am using the very latest source of libtorrent (from branch RC_1_1), in respect of the most recent provided API (I have disabled deprecated functions, with the custom build flag deprecated-functions=off).
2. Yes I plan to keep up to date with the latest releases.
3. As I have mentioned before, only a very few part of the API have been ported (which enables to add a torrent, remove it, start a download, pause, resume, stop, query torrent status and being able to download sequentially).
