### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by KhanhNB** [bbougot/libtorrent-net#3]
Hi, can you make an UWP version of libtorrent-net?

**Comment by bbougot** [comment]
I wanted to dig into it, but this is a hard task. I don't know when I will be able to do it.
If you want to move forward, first build Boost for UWP using  https://github.com/wpbest/Boost and try building libtorrent for UWP (x86, arm). 
Then, the hard part, you will have to re-create a wrapper in C++/CX (not using C++/CLI like this project).

**Comment by KhanhNB** [comment]
There is another lib, Monotorrent, that can implement bittorrent for UWP app. I tried to run this project https://github.com/haroldma/Universal.Torrent but it cannot connect to any peer. I also tried to telnet to peer but failed. Have you ever tried it before? Do you have any suggestions to fix it?

**Comment by bbougot** [comment]
I have tried MonoTorrent in the past, but had a poor experience with it. I also could not be able to connect to any peer, which led me to fork libtorrent-net

**Comment by KhanhNB** [comment]
Do you know any way that can implement BitTorrent protocol for UWP?

**Comment by bbougot** [comment]
No I don't
