### ISSUE TITLE
State value not returned by torrent_status class.

### ISSUE THREAD

**Issue by midium** [bbougot/libtorrent-net#6]
As reported by libtorrent documentation [https://www.libtorrent.org/reference-Core.html#torrent-status](https://www.libtorrent.org/reference-Core.html#torrent-status) there is a **status** property exposing a value from an internal enum that is useful to understand the status of the download process.

This is not exposed by the _torrent_status_ class of the ported implementation.

**Comment by fotis89** [comment]
I have added this functionality and created a pull request #7

**Comment by bbougot** [comment]
Seems fine to me, PR merged.
